name: publish-pypi
on: { push: { tags: ["v*"] } }
permissions: { contents: read }
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install build twine
      - run: python -m build
      - env: { TWINE_USERNAME: __token__, TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} }
        run: twine upload dist/*
